### ISSUE TITLE
Hey chun

### ISSUE THREAD

**Issue by jkille** [chunZeng/learngit#1]
Why are you hacking me? Ddossed and crashed 3 pcs and 2 phones and infected at least 15 devices? Aren't you my damn neighbor?!

**Comment by chunZeng** [comment]
i have no idea.can you describe it with more detail.

**Comment by jkille** [comment]
You live in Tacoma Washington. And files with your name on them are in my
hacked devices. Wtf is new super. 3, 11. Zygote. Schemas oracle?? I've lost
at least 3 or 4 thousand dollars being hacked. And I don't even know why or
anything.

**Comment by jkille** [comment]
And u worked or work for google. Probably using their servers cus I'm
getting way too  many google connects. I'm pretty sure it's you. I deleted
your files out of that hp stream didn't I. Pissed you off? I just need
closure. This is shitty af

**Comment by chunZeng** [comment]
it's not me. You've got the wrong perso, and don't bother me again.

**Comment by jkille** [comment]
Mhm don't be mad u got caught by a amateur. u left a million clues like
unwanted to be caught.

What are the odds I find Chinese files in my old PC and delete them. Lots
of pinyin. And then right away I get hacked bad and there's more Chinese
and pinyin and shit. And ur name comes up. It fits dude. Stop fucking with
my family. The joke is over. Keyboard warrior for life 😝😝😝😝😹😝😹😹

**Comment by jkille** [comment]
Oh and noww there's pinyin in my good search. Comm..monnnnnn fuck off dude.
Ur looking at like 40 years in prison

**Comment by chunZeng** [comment]
i'm not mad, i'm trying to talk to you peacefully.
if you really want to work that out, then you shouldn't come after me. because i absolutely have no fucking clue about what you are talking about.

**Comment by jkille** [comment]
On May 28, 2021 10:30 AM, ***@***.*** wrote:

Okay I found this.
On May 28, 2021 5:02 AM, "chunZeng" ***@***.***> wrote:

i'm not mad, i'm trying to talk to you peacefully.
if you really want to work that out, then you shouldn't come after me.
because i absolutely have no fucking clue about what you are talking about.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chunZeng/learngit/issues/1#issuecomment-850369473>, or
unsubscribe

**Comment by jkille** [comment]
Okay I found this.
